### ISSUE TITLE
Qryn exporter use local tables when clustered_clickhouse is true

### ISSUE THREAD

**Issue by hotoroy** [metrico/otel-collector#115]
```yaml
  exporters:
    qryn:
      clustered_clickhouse: true
      sending_queue:
        num_consumers: 25
        queue_size: 20000
```

i think https://github.com/metrico/otel-collector/blob/7afc304bd172b3d3689facf11691f7c7eae058e6/exporter/qrynexporter/schema.go#L24
need use _dist suffix when insert rows for correct work. 
I use `0.0.14` version collector 
We declare clustered_clickhouse: true, but this does not affect anything, local tables are used instead of clustered ones.
