### ISSUE TITLE
Health extension started to fail after upgrade from 0.0.11 to 0.0.19

### ISSUE THREAD

**Issue by tomershafir** [metrico/otel-collector#128]
After upgrading `qryn-otel-collector` from 0.0.11 to 0.0.19, without changing the configuration, health extension started to fail with:

`  Warning  Unhealthy  1s (x15 over 2m11s)  kubelet            Readiness probe failed: Get "http://10.43.102.172:13133/": dial tcp 10.43.102.172:13133: connect: connection refused`

Config:

```
receivers:
  pyroscopereceiver:
    protocols:
      http:
        endpoint: 0.0.0.0:8080

processors:
  batch:
    send_batch_size: redacted
    timeout: redacted

exporters:
  clickhouseprofileexporter:
    dsn: redacted
    timeout: redacted
    sending_queue:
      enabled: redacted
      queue_size: redacted
      num_consumers: redacted
    retry_on_failure:
      enabled: redacted
      initial_interval: redacted
      max_interval: redacted
      max_elapsed_time: redacted

extensions:
  health_check:
  pprof:
    mutex_profile_fraction: redacted
    block_profile_fraction: redacted
  zpages:

service:
  telemetry:
    metrics:
      level: detailed
    logs:
      level: redacted
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs/profiles:
      receivers: [pyroscopereceiver]
      processors: [batch]
      exporters: [clickhouseprofileexporter]
```
