### ISSUE TITLE
k8s_events -> qryn not inserting `attributes` or `resources.attributes` labels

### ISSUE THREAD

**Issue by awesense-paul** [metrico/otel-collector#134]
With the following configuration, only `Body` + `Severity.text` aka `level` are inserted (I checked this in CH `time_series_gin` table):

```
    receivers:
      k8s_events:
        namespaces: [<redacted>]
    exporters:
      qryn/gigapipe:
        dsn: tcp://<redacted>:9000/default?username=<redacted>password=<redacted>
        timeout: 10s
        sending_queue:
          queue_size: 100
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
        logs:
          format: raw
    service:
      pipelines:
        logs/k8s_events:
          receivers: [k8s_events]
          processors: []
          exporters: [qryn/gigapipe]
```

I don't have this issue with a `filelog` receiver (instead of `k8s_events`) as follows; in this case all the `attributes` + `resource_attributes` get inserted into CH:
```
      filelog:
        include_file_name: false
        include_file_path: true
        include:
          - /var/log/pods/*/*/*.log
        operators:
          - id: container-parser
            type: container
```

**Comment by shivanshs9** [comment]
I am facing this issue as well. I've raised a PR to fix it in the code to pass-through all attrs to Loki stream labels: https://github.com/metrico/otel-collector/pull/145

For now, as an interim fix, I am using this processor to transform my OTLP resource/log attributes to support the buggy logic in the qrynexporter:
```
processors:
  transform/loki-labels:
    error_mode: ignore
    # Two steps required for qryn logs exporter (eg, k8seventsreceiver):
    # 1) Rename/copy OTLP attrs → snake_case on resource (LogQL-safe; dotted keys removed).
    # 2) Set loki.resource.labels hint listing those keys — qryn only indexes hinted
    #    resource attrs when loki.attribute.labels=level is present
    # https://github.com/metrico/otel-collector/issues/134.
    log_statements:
      - context: resource
        statements:
          # Container / workload logs (resource attrs).
          - set(resource.attributes["deployment_environment"], resource.attributes["deployment.environment"]) where resource.attributes["deployment.environment"] != nil
          - set(resource.attributes["k8s_cluster_name"], resource.attributes["k8s.cluster.name"]) where resource.attributes["k8s.cluster.name"] != nil
          - set(resource.attributes["k8s_namespace_name"], resource.attributes["k8s.namespace.name"]) where resource.attributes["k8s.namespace.name"] != nil
          - set(resource.attributes["k8s_container_name"], resource.attributes["k8s.container.name"]) where resource.attributes["k8s.container.name"] != nil
          - set(resource.attributes["k8s_deployment_name"], resource.attributes["k8s.deployment.name"]) where resource.attributes["k8s.deployment.name"] != nil
          - set(resource.attributes["k8s_job_name"], resource.attributes["k8s.job.name"]) where resource.attributes["k8s.job.name"] != nil
          - set(resource.attributes["k8s_daemonset_name"], resource.attributes["k8s.daemonset.name"]) where resource.attributes["k8s.daemonset.name"] != nil
          - set(resource.attributes["k8s_statefulset_name"], resource.attributes["k8s.statefulset.name"]) where resource.attributes["k8s.statefulset.name"] != nil
          - set(resource.attributes["signoz_component"], resource.attributes["signoz.component"]) where resource.attributes["signoz.component"] != nil
          - set(resource.attributes["os_type"], resource.attributes["os.type"]) where resource.attributes["os.type"] != nil
          - set(resource.attributes["service_name"], resource.attributes["service.name"]) where resource.attributes["service.name"] != nil
          - set(resource.attributes["node_system_log"], resource.attributes["node.system.log"]) where resource.attributes["node.system.log"] != nil
          # k8s events receiver: involved object + node (resource attrs).
          - set(resource.attributes["k8s_object_kind"], resource.attributes["k8s.object.kind"]) where resource.attributes["k8s.object.kind"] != nil
          - set(resource.attributes["k8s_object_name"], resource.attributes["k8s.object.name"]) where resource.attributes["k8s.object.name"] != nil
          - set(resource.attributes["k8s_object_api_version"], resource.attributes["k8s.object.api_version"]) where resource.attributes["k8s.object.api_version"] != nil
          - set(resource.attributes["k8s_object_fieldpath"], resource.attributes["k8s.object.fieldpath"]) where resource.attributes["k8s.object.fieldpath"] != nil
          - set(resource.attributes["k8s_object_resource_version"], resource.attributes["k8s.object.resource_version"]) where resource.attributes["k8s.object.resource_version"] != nil
          - set(resource.attributes["k8s_object_uid"], resource.attributes["k8s.object.uid"]) where resource.attributes["k8s.object.uid"] != nil
          - set(resource.attributes["k8s_node_name"], resource.attributes["k8s.node.name"]) where resource.attributes["k8s.node.name"] != nil
          - set(resource.attributes["k8s_node_uid"], resource.attributes["k8s.node.uid"]) where resource.attributes["k8s.node.uid"] != nil
          # Do not set loki.resource.labels here — key contains dots, deleted below.
          - delete_matching_keys(resource.attributes, ".*\\..*")
          - delete_key(resource.attributes, "host.name")
          - delete_key(resource.attributes, "log.file.path")
          - delete_key(resource.attributes, "log.iostream")
          - delete_key(resource.attributes, "logtag")
      - context: log
        statements:
          - set(resource.attributes["level"], log.severity_text) where log.severity_text != nil and resource.attributes["level"] == nil
          - set(resource.attributes["level"], log.attributes["level"]) where log.attributes["level"] != nil
          # k8s events receiver: event fields on log attributes → resource.
          - set(resource.attributes["k8s_namespace_name"], log.attributes["k8s.namespace.name"]) where log.attributes["k8s.namespace.name"] != nil and resource.attributes["k8s_namespace_name"] == nil
          - set(resource.attributes["k8s_event_reason"], log.attributes["k8s.event.reason"]) where log.attributes["k8s.event.reason"] != nil
          - set(resource.attributes["k8s_event_action"], log.attributes["k8s.event.action"]) where log.attributes["k8s.event.action"] != nil and log.attributes["k8s.event.action"] != ""
          - set(resource.attributes["k8s_event_count"], log.attributes["k8s.event.count"]) where log.attributes["k8s.event.count"] != nil
          - set(resource.attributes["k8s_event_name"], log.attributes["k8s.event.name"]) where log.attributes["k8s.event.name"] != nil
          - set(resource.attributes["k8s_event_uid"], log.attributes["k8s.event.uid"]) where log.attributes["k8s.event.uid"] != nil
          - set(resource.attributes["k8s_event_start_time"], log.attributes["k8s.event.start_time"]) where log.attributes["k8s.event.start_time"] != nil
          - set(resource.attributes["k8s_event_reporting_controller"], log.attributes["k8s.event.reporting_controller"]) where log.attributes["k8s.event.reporting_controller"] != nil
          - set(resource.attributes["k8s_event_reporting_instance"], log.attributes["k8s.event.reporting_instance"]) where log.attributes["k8s.event.reporting_instance"] != nil
          - set(resource.attributes["source"], log.attributes["source"]) where log.attributes["source"] != nil and resource.attributes["source"] == nil
          - set(resource.attributes["service_name"], log.attributes["service.name"]) where log.attributes["service.name"] != nil and resource.attributes["service_name"] == nil
          # qryn hint — must list every snake_case key above that should be a Loki label.
          # https://github.com/metrico/otel-collector/issues/134
          - set(resource.attributes["loki.resource.labels"], "deployment_environment,k8s_cluster_name,k8s_namespace_name,k8s_container_name,k8s_deployment_name,k8s_job_name,k8s_daemonset_name,k8s_statefulset_name,signoz_component,os_type,service_name,node_system_log,k8s_object_kind,k8s_object_name,k8s_object_api_version,k8s_object_fieldpath,k8s_object_resource_version,k8s_object_uid,k8s_node_name,k8s_node_uid,k8s_event_reason,k8s_event_action,k8s_event_count,k8s_event_name,k8s_event_uid,k8s_event_start_time,k8s_event_reporting_controller,k8s_event_reporting_instance,source,level")
          - delete_key(log.attributes, "level") where log.attributes["level"] != nil
          - delete_key(log.attributes, "source") where log.attributes["source"] != nil
          - delete_key(log.attributes, "service.name") where log.attributes["service.name"] != nil
          - delete_key(log.attributes, "k8s.namespace.name") where log.attributes["k8s.namespace.name"] != nil
          - delete_matching_keys(log.attributes, "^k8s\\.event\\..*")
          - delete_key(log.attributes, "log.file.path")
          - delete_key(log.attributes, "log.iostream")
          - delete_key(log.attributes, "logtag")
```
